<a href="https://colab.research.google.com/github/RedsAnalysis/Neural-network-on-paper-from-scratch-/blob/main/Neural_network_using_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [394]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [395]:
data1 = pd.read_csv("mnist_test.csv")
data2 = pd.read_csv("mnist_train.csv")
df = pd.concat([data1, data2], axis=0)

In [396]:
train, val , test = np.split(df.sample(frac=1), [int(0.7*len(df)), int(0.85*len(df))])

In [397]:
data_train = np.array(train)
data_val = np.array(val)
data_test = np.array(test)

In [398]:
def split_features_labels(data):
  # Labels are in the first column
    y = data[0::,0:1]
    # Features are all the other columns
    x = data[0::,1::]
    return x, y

In [399]:
X_train, y_train = split_features_labels(data_train)
X_val, y_val = split_features_labels(data_val)
X_test, y_test = split_features_labels(data_test)

In [400]:
X_train.shape

(49000, 784)

In [401]:
X = X_train[:1]
X.shape
y = y_train[:1]

In [402]:
X1 =X
y1=y

In [403]:
y1 = y1.T

In [404]:
y1.shape

(1, 1)

In [405]:
X1 = X.T

In [406]:
X1.shape

(784, 1)

In [407]:
import numpy as np

# Global variables for weights and biases
w1, w2, w3, b1, b2, b3 = None, None, None, None, None, None

def initialize_network(input_size, hidden_size1, hidden_size2, output_size):
    global w1, w2, w3, b1, b2, b3
    # Weights are initialized with small random values
    w1 = np.random.randn(hidden_size1, input_size) * 0.01
    w2 = np.random.randn(hidden_size2, hidden_size1) * 0.01
    w3 = np.random.randn(output_size, hidden_size2) * 0.01
    # Biases are initialized to zeros
    b1 = np.zeros((hidden_size1,1))
    b2 = np.zeros((hidden_size2,1))
    b3 = np.zeros((output_size,1))



In [408]:
initialize_network(784, 16,16,10)

In [409]:
w1.shape

(16, 784)

In [410]:

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def softmax(x):
    return np.exp(x) / np.sum(exp(x))



def sigmoid_derivative(x):
    return x * (1 - x)


In [411]:
def forward_pass(X):
    Z1 = np.dot(w1, X) + b1
    A1 = sigmoid(Z1)
    Z2 = np.dot(w2, A1) + b2
    A2 = sigmoid(Z2)
    Z3 = np.dot(w3, A2) + b3
    output = sigmoid(Z3)
    return A1, A2, output

def compute_loss(output, y):
    m = y.shape[1]
    logprobs = np.multiply(np.log(output), y) + np.multiply((1 - y), np.log(1 - output))
    loss = -np.sum(logprobs) / m
    return loss


In [412]:
forward(X1)

(array([[0.49850627],
        [0.4985442 ],
        [0.49811027],
        [0.49885037],
        [0.49462579],
        [0.50522054],
        [0.49899049],
        [0.50341378],
        [0.50333744],
        [0.50284049]]),
 array([[7.25472305e-01],
        [9.99999967e-01],
        [9.99940974e-01],
        [2.05255337e-35],
        [1.45816552e-16],
        [1.39117480e-05],
        [1.00000000e+00],
        [1.68303183e-08],
        [9.99999963e-01],
        [1.00000000e+00],
        [2.82304065e-17],
        [2.66542227e-14],
        [1.00000000e+00],
        [9.99999900e-01],
        [2.73649988e-30],
        [9.85381377e-01]]),
 array([[0.51443756],
        [0.49661295],
        [0.50142417],
        [0.50582442],
        [0.48900035],
        [0.50674464],
        [0.49723129],
        [0.4940851 ],
        [0.49603079],
        [0.49971404],
        [0.49752444],
        [0.50387492],
        [0.49290283],
        [0.5070188 ],
        [0.49330635],
        [0.49760526]]))

In [413]:
w3.shape

(10, 16)

In [419]:
def backprop(X, y, A1, A2, output, learning_rate=0.01):
    global w1, w2, w3, b1, b2, b3

    # Output layer error
    output_error = output - y
    output_delta = output_error * sigmoid_derivative(output)

    # Error for Hidden Layer 2
    A2_error = w3.T.dot(output_delta)
    A2_delta = A2_error * sigmoid_derivative(A2)

    # Error for Hidden Layer 1
    A1_error = w2.T.dot(A2_delta)
    A1_delta = A1_error * sigmoid_derivative(A1)

    # Update weights and biases
    w3 -= learning_rate * output_delta.dot(A2.T)
    b3 -= learning_rate * np.sum(output_delta, axis=1, keepdims=True)

    w2 -= learning_rate * A1.dot(A2_delta.T)
    b2 -= learning_rate * np.sum(A2_delta, axis=1, keepdims=True)

    w1 -= learning_rate * X.T.dot(A1_delta)
    b1 -= learning_rate * np.sum(A1_delta, axis=1, keepdims=True)


In [422]:
def train(X, y, epochs, learning_rate=0.01):
    for epoch in range(epochs):
        A1, A2, output = forward_pass(X)
        loss = compute_loss(output, y)
        backprop(X, y, A1, A2, output, learning_rate)
        if epoch % 1 == 0:  # Modify as needed for less frequent logging
            print(f"Epoch {epoch+1}, Loss: {loss:.4f}")

# Example call
train(X1, y1, epochs, learning_rate=0.01)


ValueError: shapes (1,784) and (16,1) not aligned: 784 (dim 1) != 16 (dim 0)

In [421]:
print("Shape of X.T:", X.T.shape)
print("Shape of A1_delta:", A1_delta.shape)


Shape of X.T: (784, 1)


NameError: name 'A1_delta' is not defined

In [386]:
A2.shape

(16, 1)

In [387]:
output.shape

(10, 1)

In [388]:
y1.shape

(10, 1)

In [389]:
sigmoid_derivative(output).shape


(10, 1)

In [390]:
]

In [423]:
input_size = 784  # for MNIST data, each image is 28x28 pixels
hidden_size1 = 16
hidden_size2 = 16
output_size = 10  # assuming a classification task with 10 classes
epochs = 10

# Initialize the network
initialize_network(input_size, hidden_size1, hidden_size2, output_size)

# Assuming X and y are already loaded and preprocessed
train(X1, y1, epochs, learning_rate=0.01)


ValueError: shapes (1,784) and (16,1) not aligned: 784 (dim 1) != 16 (dim 0)

In [393]:

# Assuming y1 is a target vector for a batch of examples
if y1.shape[0] != output_size:
    print("Mismatch in the target shape and output layer configuration.")
    print("Target shape received:", y1.shape)
    print("Expected shape:", (output_size, y1.shape[1]))
else:
    print("okay")


okay
